hosting/urls.py
from django.urls import path

from hosting.views import HomePageView, ImageView, UploadView, ImageListView, RemoveImageView

app_name = 'hosting'

urlpatterns = [
    path('', HomePageView.as_view(), name="home_page"),
    path('upload/', UploadView.as_view(), name="upload_handler"),
    path('view/<int:pk>', ImageView.as_view(), name="image_view"),
    path('list/', ImageListView.as_view(), name="image_list"),
    path('remove/<int:pk>', RemoveImageView.as_view(), name="image_remove")
]

test5/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hosting.urls', namespace="hosting")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hosting/models.py
import hashlib

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as _
from exiffield.fields import ExifField
from model_utils import FieldTracker


def hash_file_object(file_object):
    """
    Hash uploaded file

    :param file_object: Django input file object
    :type file_object: FieldFile|ImageFieldFile
    :return: hash digest
    :rtype: str
    """
    hash_object = hashlib.sha256()
    for chunk in iter(lambda: file_object.read(4096), b""):
        hash_object.update(chunk)

    return hash_object.hexdigest()


class HostedImage(models.Model):

    name = models.CharField(_("image name"), max_length=1000)
    image_file = models.ImageField(_("image file"), upload_to="uploads/")
    exif = ExifField(source='image_file')
    upload_date = models.DateTimeField(_("upload date"), default=timezone.now)
    sha256_checksum = models.CharField(_("checksum"), max_length=64, db_index=True, unique=True)
    image_file_tracker = FieldTracker(fields=['image_file'])

    def save(self, *args, **kwargs):
        if self.image_file_tracker.changed():
            self.image_file.file.seek(0)
            self.sha256_checksum = hash_file_object(self.image_file.file)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('hosting:image_view', args=(self.id,))

    class Meta:
        verbose_name = _("image file")
        verbose_name_plural = _("image files")

    def __str__(self):
        return self.name

hosting/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

from hosting.models import HostedImage, hash_file_object


class ImageFileUploadForm(forms.ModelForm):

    def clean(self):
        super().clean()
        image_file = self.cleaned_data.get('image_file')
        if not image_file:
            raise ValidationError(
                {"image_file": _("image file is corrupted or too big")}, code='invalid'
            )

        image_file.file.seek(0)
        sha256_hash = hash_file_object(image_file)
        if HostedImage.objects.filter(sha256_checksum=sha256_hash).exists():
            raise ValidationError(
                {"image_file": _("same image file already exists")}, code='invalid'
            )

        return self.cleaned_data

    class Meta:
        model = HostedImage
        fields = ('name', 'image_file')

hosting/views.py
from django.urls import reverse
from django.views.generic import FormView, DetailView, CreateView, ListView, DeleteView

from hosting.forms import ImageFileUploadForm
from hosting.models import HostedImage


class HomePageView(FormView):

    template_name = "index.html"
    form_class = ImageFileUploadForm


class UploadView(CreateView):

    form_class = ImageFileUploadForm
    template_name = "index.html"


class ImageView(DetailView):

    model = HostedImage
    context_object_name = "image"
    template_name = "image_view.html"


class ImageListView(ListView):

    queryset = HostedImage.objects.all()
    paginate_by = 10
    context_object_name = "images"
    template_name = "image_list.html"


class RemoveImageView(DeleteView):

    model = HostedImage

    def get_success_url(self):
        return "{}?remove=success".format(reverse("hosting:image_list"))

hosting/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% trans "default title" %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

hosting/templates/image_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}
{% block title %}{% trans "image list" %}{% endblock %}
{% block body %}
    <div class="container-fluid">
      {% if request.GET.remove == 'success' %}
          <div class="alert alert-primary" role="alert">
            {% trans "image has been removed successfully" %}
          </div>
      {% elif request.GET.remove == 'failed' %}
          <div class="alert alert-danger" role="alert">
            {% trans "can't remove image" %}
          </div>
    {% endif %}

    {% for image in images %}
        <div class="row">
            <div class="col-sm-2">
                {% thumbnail image.image_file "200x200" format="PNG" as image_thumb %}
                    <a href="{{ image.image_file.url }}"><img src="{{ image_thumb.url }}" alt="{{ image.name }}" class="img-thumbnail"></a>
                {% endthumbnail %}
            </div>
            <div class="col-sm-4">
                <table class="table">
                    <tbody>
                        <tr>
                          <th>{% trans "image name" %}</th>
                            <td>{{ image.name }}</td>
                        </tr>
                        <tr>
                          <th>{% trans "camera" %}</th>
                            <td>{{ image.exif.Make.val|default:_("unknown manufacturer") }} {{ image.exif.Model.val|default:_("unknown model") }}</td>
                        </tr>
                        <tr>
                          <th>{% trans "file size" %}</th>
                            <td>{{ image.image_file.size|filesizeformat }}</td>
                        </tr>
                        <tr>
                          <th>{% trans "date taken" %}</th>
                            <td>{{ image.exif.DateTimeOriginal.val|default:_("unknown") }}</td>
                        </tr>
                        <tr>
                          <th>{% trans "uploaded" %}</th>
                            <td>{{ image.upload_date }}</td>
                        </tr>
                        <tr>
                          <th>{% trans "actions" %}</th>
                          <td>
                              <form name="remove-image" method="post" action="{% url "hosting:image_remove" image.pk %}">
                                  {% csrf_token %}
                                <button class="btn btn-danger" type="submit">{% trans "delete" %}</button>
                              </form>
                          </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    {% endfor %}
    <nav aria-label="Pages">
      <ul class="pagination">
        <li class="page-item"><a class="page-link" href="{{ paginator.previous_page_number }}">{% trans "previous" context "pagination" %}</a></li>
          {% for page in paginator.page_range %}
              <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
          {% endfor %}
        <li class="page-item"><a class="page-link" href="{{ paginator.next_page_number }}">{% trans "next" context "pagination" %}</a></li>
      </ul>
    </nav>
    </div>
{% endblock %}

hosting/templates/image_view.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n %}
{% block title %}{% trans "image" %} {{ image.name }}{% endblock %}
{% block body %}
{% thumbnail image.image_file "200x200" format="PNG" as image_thumb %}
    <a href="{{ image.image_file.url }}"><img src="{{ image_thumb.url }}" alt="{{ image.name }}" class="img-thumbnail"></a>
{% endthumbnail %}
    <table class="table">
        <tbody>
            <tr>
              <th>{% trans "image name" %}</th>
                <td>{{ image.name }}</td>
            </tr>
            <tr>
              <th>{% trans "camera" %}</th>
                <td>{{ image.exif.Make.val|default:"<i>unknown manufacturer</i>" }} {{ image.exif.Model.val|default:"<i>unknown model</i>" }}</td>
            </tr>
            <tr>
              <th>{% trans "file size" %}</th>
                <td>{{ image.image_file.size|filesizeformat }}</td>
            </tr>
            <tr>
              <th>{% trans "date taken" %}</th>
                <td>{{ image.exif.DateTimeOriginal.val }}</td>
            </tr>
            <tr>
              <th>{% trans "uploaded" %}</th>
                <td>{{ image.upload_date }}</td>
            </tr>
            <tr>
              <th>{% trans "actions" %}</th>
              <td>
                  <form name="remove-image" method="post" action="{% url "hosting:image_remove" image.pk %}">
                      {% csrf_token %}
                      <button class="btn btn-danger" type="submit">{% trans "delete" %}</button>
                  </form>
              </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

hosting/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "welcome to image hosting!" %}{% endblock %}
{% block body %}
    <div class="container-fluid">
<form name="image-upload" method="post" action="{% url "hosting:upload_handler" %}" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="form-group{%if field.image_file.errors %} error{%endif%}">
    <label for="{{ form.image_file.name }}">{% trans "image name" %}</label>
    {{ form.name }}
      <p class="text-danger">{{ form.name.errors }}</p>
  </div>
  <div class="form-group{%if field.image_file.errors %} error{%endif%}">
    <label for="{{ form.image_file.id_for_label }}">{% trans "image file" %}</label>
    {{ form.image_file }}
     <small id="uploadFieldInfo" class="text-muted">
      {% trans "max file size is" %}: 10 MB
    </small>
      <p class="text-danger">{{ form.image_file.errors }}</p>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="{% trans "upload" %}">
  </div>
</form>
    <p><a href="{% url "hosting:image_list" %}">{% trans "image list" %}</a></p>
    </div>

{% endblock %}